### ISSUE TITLE
请问这是你重译的还是fork BrambleXu的呢？

### ISSUE THREAD

**Issue by jiahe224** [iamseancheney/python_for_data_analysis_2nd_chinese_version#12]
要是重译的我再看看，BrambleXu 的我之前看了

**Comment by WangYe661** [comment]
fork的

________________________________
发件人: jiahe224 <notifications@github.com>
发送时间: Thursday, May 28, 2020 10:09:39 AM
收件人: iamseancheney/python_for_data_analysis_2nd_chinese_version <python_for_data_analysis_2nd_chinese_version@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [iamseancheney/python_for_data_analysis_2nd_chinese_version] 请问这是你重译的还是fork BrambleXu的呢？ (#12)


要是重译的我再看看，BrambleXu 的我之前看了

―

**Comment by jiahe224** [comment]
对比了一下，不完全一样，这个更详细，不知原版是哪位呢 @iamseancheney

**Comment by WangYe661** [comment]
这个是fork的，时间太久想不起来来源，抱歉不能给你提供有用的信息

王钟锐
________________________________
发件人: jiahe224 <notifications@github.com>
发送时间: Friday, November 6, 2020 11:01:53 AM
收件人: iamseancheney/python_for_data_analysis_2nd_chinese_version <python_for_data_analysis_2nd_chinese_version@noreply.github.com>
抄送: WangYe661 <wangye661@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [iamseancheney/python_for_data_analysis_2nd_chinese_version] 请问这是你重译的还是fork BrambleXu的呢？ (#12)


对比了一下，不完全一样，这个更详细，不知原版是哪位呢 @iamseancheney<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiamseancheney&data=04%7C01%7C%7C45ff1dbd5d284f45a65a08d8820050f5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637402285150592028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XMTHk%2F0D3%2Bpz2Mon8oJO4UtfEL3da%2FfUDnvWLVOzgB8%3D&reserved=0>

―
